name: Build a KMM Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-  

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

#      - name: Setup JDK
#        uses: actions/setup-java@v2
#        with:
#          java-version: '11'

#      - name: Setup KMM
#        uses: kotlin-actions/setup-kmm@v1

#      - name: Build KMM Project
#        run: ./gradlew build

#      - name: Build Android App
#        uses: strvcom/setup-android-build-environment@v2
#        with:
#          target-sdk: "31"
#        run: ./gradlew :androidApp:assembleDebug

      - name: Setup Swift
        uses: swift-actions/setup-swift@v1

      - name: Build iOS App
        run: |
          cd iosApp
          xcodebuild -workspace iosApp.xcworkspace -scheme iosApp -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 13' build test

#      - name: Deploy Android App
#        uses: actions/upload-artifact@v2
#        with:
#          name: Android App
#          path: androidApp/build/outputs/apk/debug/androidApp-debug.apk
#
#      - name: Deploy iOS App
#        uses: actions/upload-artifact@v2
#        with:
#          name: iOS App
#          path: iosApp/build/Debug-iphonesimulator/iosApp.app
